- name: Ensure SSH configurations are up to date.
  ansible.builtin.template:
    src: "etc/ssh/sshd_config.d/{{ item }}.j2"
    dest: "/etc/ssh/sshd_config.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart ssh
  with_items: 
    - spin-secure-ssh.conf
    - spin-ssh-tunnels.conf

- name: Configure sudo access for sudo group
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: "{{ 'present' if use_passwordless_sudo | default(false) else 'absent' }}"
    regexp: '^%sudo\s+ALL=\(ALL\)\s+NOPASSWD:\s+ALL'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Open the firewall port for SSH.
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: "tcp"
    comment: "Allow SSH connections."
  notify: Enable ufw

- name: Ensure umask is set in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^UMASK'
    line: 'UMASK 022'
    state: present

- name: Disable USERGROUPS_ENAB in /etc/login.defs
  ansible.builtin.lineinfile:
    path: /etc/login.defs
    regexp: '^USERGROUPS_ENAB'
    line: 'USERGROUPS_ENAB no'
    state: present

- name: Set umask in /etc/profile
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: 'umask 022'
    state: present