- name: Ensure secure SSH config is up to date.
  ansible.builtin.template:
    src: "etc/ssh/sshd_config.d/spin-secure-ssh.conf.j2"
    dest: "etc/ssh/sshd_config.d/spin-secure-ssh.conf"
    owner: root
    group: root
    mode: 0644
  notify: Restart ssh

- name: Open the firewall port for SSH.
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: "tcp"
    comment: "Allow SSH connections."
  notify: Enable ufw