- name: Disallow root SSH access.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart ssh

- name: Set SSH port.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ server_ssh_port }}"
    state: present
  notify: Restart ssh

- name: Disallow password authentication over SSH.
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart ssh

- name: Open the firewall port for SSH.
  community.general.ufw:
    rule: allow
    port: "{{ server_ssh_port }}/tcp"
    comment: "Allow SSH connections."
    state: present
  notify: Enable ufw