---
- name: Find Dockerfiles
  find:
    paths: "{{ ansible_env.PWD }}"
    patterns: "Dockerfile*"
  register: dockerfiles

- name: Build Docker images locally
  command: >
    docker buildx build --platform {{ build_platform }} -f {{ item.path }} -t "{{ build_prefix }}/{{ item.path | regex_replace('^.*Dockerfile\\.', '') }}:{{ build_tag }}" --load
  loop: "{{ dockerfiles.files }}"
  register: build_result
  failed_when: build_result.rc != 0
  changed_when: "'Successfully built' in build_result.stdout"

- name: Set fact for Docker images and IDs
  set_fact:
    docker_images: "{{ build_result.results | map(attribute='stdout_lines') | list }}"