---
- name: Find all Dockerfiles
  find:
    paths: "{{ project_path}}"
    patterns: "Dockerfile*"
  register: dockerfiles
  delegate_to: localhost

- name: Build Docker images
  community.docker.docker_image:
    path: "{{ item.path }}"
    name: "{{ item.path | regex_replace('^.*/Dockerfile\\.?(.*)$', '\\1') | default('image', true) }}"
    source: build
  loop: "{{ dockerfiles.files }}"
  delegate_to: localhost