---
- name: Find Dockerfiles
  find:
    paths: "{{ ansible_env.PWD }}"
    patterns: 'Dockerfile*'
  register: dockerfiles

- debug:
    var: dockerfiles

- name: Fail if no Dockerfiles are found
  fail:
    msg: "❌ No Dockerfiles found in this directory. Be sure to run 'spin deploy' in your project root."
  when: dockerfiles.matched == 0