---
namespace: serversideup
name: spin
version: 0.0.1-5
readme: README.md
authors:
  - Jay Rogers (https://x.com/jaydrogers)
description: The Spin Collection is a collection of Ansible roles that can be used to spin up a Linux server with Docker Swarm.
license_file: LICENSE
tags:
  - serversideup
  - spin
  - linux
  - docker
  - swarm
dependencies:
  serversideup.linux_common: '*'
  serversideup.docker_swarm: '*'
repository: https://github.com/serversideup/ansible-collection-spin
documentation: https://release-2-0.ssu-spin.pages.dev/docs
homepage: https://release-2-0.ssu-spin.pages.dev/
issues: https://github.com/serversideup/ansible-collection-spin/issues
build_ignore:
  - 'new-version.sh'
