- name: Ensure the Docker user's group exists with the correct GID.
  ansible.builtin.group:
    name: "{{ docker_user.group }}"
    gid: "{{ docker_user.gid }}"
    state: present

- name: Ensure the Docker user is created.
  ansible.builtin.user:
    name: "{{ docker_user.username }}"
    create_home: yes
    group: "{{ docker_user.group }}"
    groups: "{{ docker_user.secondary_groups }}"
    home: "{{ docker_user.home | default(omit) }}"
    shell: /bin/bash
    state: present
    system: no
    uid: "{{ docker_user.uid }}"

- name: Set the authorized SSH keys for the Docker user.
  ansible.posix.authorized_key:
    user: "{{ docker_user.username }}"
    state: present
    key: "{{ item }}"
  with_items: "{{ docker_user.authorized_ssh_keys }}"
  when: docker_user.authorized_ssh_keys is defined

- name: Add public keys of admin or sudo users to Docker user
  ansible.posix.authorized_key:
    user: "{{ docker_user.username }}"
    state: present
    key: "{{ item.authorized_keys.0.public_key }}"
  loop: "{{ users }}"
  when: "'adm' in item.groups or 'sudo' in item.groups"