- name: Initialize Docker Swarm.
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm.advertise_addr }}"
  when: "'swarm_managers' in group_names"

- name: Open HTTP and HTTPS ports (TCP/UDP)
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "Allow HTTP/HTTPS connections."
  loop:
    - { port: "80", proto: "tcp" }
    - { port: "443", proto: "tcp" }
    - { port: "443", proto: "udp" }  # For HTTP/3 (QUIC)
  when: automatically_open_http_and_https_ports | bool
  notify: Enable ufw
