- name: Initialize Docker Swarm.
  community.docker.docker_swarm:
    state: present
  when: "'service_docker_swarm_all_managers' is in group_names"

- name: Open HTTP and HTTP ports (if enabled)
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: "tcp"
    comment: "Allow HTTP connections."
  loop:
    - "80"
    - "443"
  when: automatically_open_http_and_https_ports | bool
  notify: Enable ufw