---
- name: "Deploy your application with Docker over SSH (no Docker registry required)."
  hosts: "{{ target | default('none') }}"
  remote_user: "{{ ansible_user | default('root') }}"
  become: true
  vars:
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain"
  roles:
    - serversideup.spin.deploy
