---
- name: Deploy your application with Docker over SSH (no Docker registry required).
  hosts: '{{ target }}'
  remote_user: "{{ lookup('env', 'USER') }}"
  become: true
  vars:
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain -o Port={{ ssh_port | default(22) }}"
    compose_files: "{{ compose_files | default(['docker-compose.yml', 'docker-compose.prod.yml']) }}"
  roles:
    - serversideup.spin.deploy