---
- name: Deploy and maintain Docker Swarm servers with Spin.
  hosts: '{{ target | default("all") }}'
  remote_user: '{{ remote_user | default("root") }}'
  vars:
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain"
  pre_tasks:
    - name: Set ansible_ssh_port
      set_fact:
        ansible_ssh_port: "{{ server_ssh_port }}"

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Install PIP dependencies.
      pip:
        name: docker
        state: present

  roles:
    - serversideup.spin.linux_common
    - serversideup.spin.swarm