---
- name: Deploy and maintain Docker Swarm servers with Spin.
  hosts: '{{ target | default("all") }}'
  remote_user: '{{ remote_user | default("root") }}'
  become: true
  vars:
    ansible_ssh_common_args: "-o IgnoreUnknown=UseKeychain"
  pre_tasks:
    - name: Set ansible_ssh_port
      set_fact:
        ansible_ssh_port: "{{ ssh_port }}"
  roles:
    - serversideup.spin.linux_common
    - serversideup.spin.swarm